MAIN_PATH = "/home/rastekid/apps/"
FILE_ID = "file-id.txt"

# MQTT
MQTT_HOST = "10.168.1.28"
MQTT_PORT = 1883
MQTT_USERNAME = "jpo:jpo"
MQTT_PASSWORD = "rastek@jpo"
MQTT_TOPIC = "jpo/datafeed"

MINIO_ENDPOINT = "10.168.1.20:3000"
MINIO_ACCESS_KEY = "moYyVtum6mv8efr9yL9h"
MINIO_SECRET_KEY = "7bn7NZfAAclxVb9H4GSdAtpRANHdmDWEYfNSVApz"
MINIO_BUCKET_NAME = "jpo"

DURATION_GET_CONFIG = 60

BACKEND_ENDPOINT = "http://202.180.16.237:28080/"
BACKEND_AUTH_USERNAME = "comvis"
BACKEND_AUTH_PASSWORD = "C0mV!s"
BACKEND_AUTH_GRANT_TYPE = "password"
